### ISSUE TITLE
Failure on new python versions

### ISSUE THREAD

**Issue by SFuller4** [dataiku/dss-plugin-sharepoint-server#13]
@StanislasBertrand Tagging you because you merged the last version update.

The latest version update is causing a failure on the code env build in dss 11.2.1

It would appear that due to the inability to select the core packages when creating the default code environment for this plugin, the legacy pandas options 0.23.4 that is being forced is failing install on python3.8 (I'm assuming and up but we haven't tested that). 

Is there a way we can override the core packages on the code environment being generated for this plugin without going through the backend linux box?

**Comment by SFuller4** [comment]
[createPythonEnv_2023_06_02.log.gz](https://github.com/dataiku/dss-plugin-sharepoint-server/files/11638945/createPythonEnv_2023_06_02.log.gz)

Log file we get when trying to build a 3.8 environment

**Comment by StanislasBertrand** [comment]
Hi @SFuller4 , thanks for reaching out to me

Indeed this is a mistake from our part, this last release was meant only for DSS 12. It is recommended to use v1.0.2 of the plugin for DSS 11 and below, and v1.0.3 for DSS 12 and above. In any case, do not use python version higher than 3.6 with DSS 11 for the code env creation.

We will update the plugin documentation to include this information.

**Comment by SFuller4** [comment]
Thank @StanislasBertrand, we'll make those adjustments on our end and look at getting onto DSS 12 so we can update these plugins.
